chore: updating workflow to avoid conflicts

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -26,7 +26,7 @@ jobs:
         go-version: '1.22.3'
 
     - name: Build
-      run: xvfb-run -a go build -v ./...
+      run: xvfb-run -a go build -v ./... 2>&1 || (echo "Build failed with exit code $?" && exit 1)
 
     - name: Test
-      run: xvfb-run -a go test -v ./...
+      run: xvfb-run -a go test -v ./... 2>&1 || (echo "Test failed with exit code $?" && exit 1)
